### ISSUE TITLE
Problems found.

### ISSUE THREAD

**Issue by sean-m-sullivan** [sean-m-sullivan/ansiblefest2022_configuration_as_code#31]
student_num is undefined and used to be in vault, but is still referenced in credentials

Also this depends on the fix in devel of controller_configuration to use assign_default_ee_to_org , we need to make sure 2.1.10 is released or newer to use for that feature.

**Comment by sean-m-sullivan** [comment]
The later is just us doing a new release, the student num one is an easy fix, but unsure of how we want to address it.

**Comment by djdanielsson** [comment]
yea I know, I was going back and forth on if I wanted to keep it or not. Also I think the var name currently is confusing because atm it is actually looking for `student1` not just `1`.
