### ISSUE TITLE
Wrong value in Task 1 Step 7

### ISSUE THREAD

**Issue by david-igou** [sean-m-sullivan/ansiblefest2022_configuration_as_code#38]
ee_list variables use key `ee_name` when it should be `name`

https://github.com/sean-m-sullivan/ansiblefest2022_configuration_as_code/blob/main/task1.md?plain=1#L174
https://github.com/sean-m-sullivan/ansiblefest2022_configuration_as_code/blob/main/task1.md?plain=1#L184

**Comment by sean-m-sullivan** [comment]
Fixed please review.

**Comment by sean-m-sullivan** [comment]
Closing as resolved.
